-- UTF-8, rerunnable seed for the Tiệm Cà Phê Mare tenant database.
-- Listing facts (address, hours, price band) were verified on Foody/ShopeeFood.
-- Dish names were not exposed by the public listing API on 2026-08-07; these are
-- curated demo products within the published 16,000–38,000 VND price range.
CREATE UNIQUE INDEX IF NOT EXISTS uq_caphemare_productcode ON producttb(productcode) WHERE productcode LIKE 'MARE-%';
INSERT INTO producttb (productname,productcode,productcatalog,productbrand,productshortdes,productlongdes,productimageurl1,productimageurl2,productimagedesurl,productsubcatalog,productgroupstring,pagekeyword,productpriceamount,productdiscont,productpricecurrency,language,path,createdtime,publishedtime,modifiedtime,isvisible,isapproved,islocked,isnew) VALUES
('Cà Phê Sữa Đá','MARE-CA-PHE-SUA-DA','Cà phê','Tiệm Cà Phê Mare','Cà phê Việt đậm vừa, quyện sữa đặc và đá mát.','<p>Một ly quen thuộc cho buổi sáng nhẹ nhàng, cân bằng giữa vị rang thơm và chút ngọt dịu.</p>','/caphemare/images/coffee.svg','/caphemare/images/coffee.svg','/caphemare/images/coffee.svg','Cà phê Việt','caphemare-menu','cà phê sữa đá Mare Quận 6',28000,0,'VND','vi','ca-phe-sua-da',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,TRUE),
('Cà Phê Đen Đá','MARE-CA-PHE-DEN-DA','Cà phê','Tiệm Cà Phê Mare','Vị rang rõ, thơm sâu và hậu vị gọn gàng.','<p>Dành cho người thích một ly cà phê thuần khiết, tỉnh táo và không cầu kỳ.</p>','/caphemare/images/black-coffee.svg','/caphemare/images/black-coffee.svg','/caphemare/images/black-coffee.svg','Cà phê Việt','caphemare-menu','cà phê đen đá Quận 6',22000,0,'VND','vi','ca-phe-den-da',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,FALSE),
('Bạc Xỉu Mare','MARE-BAC-XIU','Cà phê','Tiệm Cà Phê Mare','Nhiều sữa, nhẹ cà phê, mềm vị và dễ uống.','<p>Phiên bản dịu dàng cho một ngày thong thả, với hương cà phê vừa đủ làm điểm nhấn.</p>','/caphemare/images/milk-coffee.svg','/caphemare/images/milk-coffee.svg','/caphemare/images/milk-coffee.svg','Cà phê sữa','caphemare-menu','bạc xỉu Mare',30000,0,'VND','vi','bac-xiu-mare',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,TRUE),
('Cà Phê Muối','MARE-CA-PHE-MUOI','Cà phê','Tiệm Cà Phê Mare','Lớp kem muối béo nhẹ ôm lấy nền cà phê đậm.','<p>Mặn rất khẽ, ngọt vừa đủ và thơm lâu — một lựa chọn tròn vị cho buổi chiều.</p>','/caphemare/images/salted-coffee.svg','/caphemare/images/salted-coffee.svg','/caphemare/images/salted-coffee.svg','Cà phê sáng tạo','caphemare-menu','cà phê muối Mare',35000,0,'VND','vi','ca-phe-muoi',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,TRUE),
('Trà Đào Cam Sả','MARE-TRA-DAO-CAM-SA','Trà trái cây','Tiệm Cà Phê Mare','Trà thơm, đào mọng cùng cam và hương sả thanh.','<p>Chua ngọt cân bằng, mát lành và hợp với những trưa Sài Gòn nhiều nắng.</p>','/caphemare/images/peach-tea.svg','/caphemare/images/peach-tea.svg','/caphemare/images/peach-tea.svg','Trà','caphemare-menu','trà đào cam sả Mare',38000,0,'VND','vi','tra-dao-cam-sa',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,FALSE),
('Trà Tắc Mật Ong','MARE-TRA-TAC-MAT-ONG','Trà trái cây','Tiệm Cà Phê Mare','Vị tắc tươi sáng, mật ong dịu và nền trà thanh.','<p>Một món giải khát nhẹ nhàng, dễ uống vào mọi thời điểm trong ngày.</p>','/caphemare/images/honey-tea.svg','/caphemare/images/honey-tea.svg','/caphemare/images/honey-tea.svg','Trà','caphemare-menu','trà tắc mật ong Quận 6',32000,0,'VND','vi','tra-tac-mat-ong',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,FALSE)
ON CONFLICT(productcode) WHERE productcode LIKE 'MARE-%' DO UPDATE SET productname=EXCLUDED.productname,productcatalog=EXCLUDED.productcatalog,productbrand=EXCLUDED.productbrand,productshortdes=EXCLUDED.productshortdes,productlongdes=EXCLUDED.productlongdes,productimageurl1=EXCLUDED.productimageurl1,productimageurl2=EXCLUDED.productimageurl2,productimagedesurl=EXCLUDED.productimagedesurl,productsubcatalog=EXCLUDED.productsubcatalog,productgroupstring=EXCLUDED.productgroupstring,pagekeyword=EXCLUDED.pagekeyword,productpriceamount=EXCLUDED.productpriceamount,productdiscont=EXCLUDED.productdiscont,productpricecurrency=EXCLUDED.productpricecurrency,language=EXCLUDED.language,path=EXCLUDED.path,modifiedtime=NOW(),isvisible=TRUE,isapproved=TRUE,islocked=FALSE,isnew=EXCLUDED.isnew;
