-- Destructive PostgreSQL demo seed for cloned tenant: hihitomyum.anhmedia.vn
-- Run ONLY against the newly cloned tenant database. Menu and prices are demo data.
BEGIN;
TRUNCATE TABLE public.articletb, public.producttb RESTART IDENTITY CASCADE;

INSERT INTO public.articletb (articleid,username,articlelink,articlecategory,articlelangcode,articlesubcategory,articletitle,articlekeyword,articlethumnailurl,articledescription,articlecontent,createdtime,modifiedtime,isvisible,isapproved,islocked,rejectedbyuser,rejectedreason,articletime,originauthor,menustringid,viewcount,rating,postid,articletemplate,"index") VALUES
('HIHI-PAGE-HOME','none','home','page','en','none','HIHI TomYum — All About Thai Noodles','HIHI TomYum, Thai noodles, Saigon','/hihitomyum/images/hihi-hero-tomyum.png','Bright, sour and spicy Thai noodles in Saigon.','<p>HIHI TomYum home page.</p>',NOW(),NOW(),TRUE,TRUE,FALSE,'none','none',NOW(),'HIHI TomYum','none',0,0,'n','index.html','0'),
('HIHI-PAGE-PRODUCTS','none','products.html','page','en','none','Menu — HIHI TomYum','Thai noodles, Tom Yum, mango sticky rice','/hihitomyum/images/hihi-feast.png','Thai noodle bowls, sharing plates and sweets.','<p>HIHI TomYum demo menu.</p>',NOW(),NOW(),TRUE,TRUE,FALSE,'none','none',NOW(),'HIHI TomYum','none',0,0,'n','products.html','1');

INSERT INTO public.producttb (productname,productcode,productcatalog,productbrand,productshortdes,productlongdes,productimageurl1,productimageurl2,productimagedesurl,productsubcatalog,productgroupstring,pagekeyword,productpriceamount,productdiscont,productpricecurrency,language,path,createdtime,publishedtime,modifiedtime,isvisible,isapproved,islocked,isnew) VALUES
('Mama Tom Yum Seafood','HIHI-MAMA-TOM-YUM-SEAFOOD','Noodle bowls','HIHI TomYum','Prawns, squid, mushrooms, lime and fragrant roasted chilli broth.','<p>A bright, aromatic bowl with the Thai balance of sour, spicy, salty and sweet.</p>','/hihitomyum/images/hihi-hero-tomyum.png','/hihitomyum/images/hihi-hero-tomyum.png','/hihitomyum/images/hihi-hero-tomyum.png','HIHI signature','hihi-menu','Tom Yum seafood, Thai noodles, HIHI',89000,0,'VND','en','mama-tom-yum-seafood',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,TRUE),
('HIHI Sharing Feast','HIHI-SHARING-FEAST','Sharing','HIHI TomYum','A colorful table of Thai favorites made for sharing.','<p>Order plenty, pass everything and share the sour-spicy joy.</p>','/hihitomyum/images/hihi-feast.png','/hihitomyum/images/hihi-feast.png','/hihitomyum/images/hihi-feast.png','For the table','hihi-menu','Thai sharing feast, HIHI TomYum',199000,0,'VND','en','hihi-sharing-feast',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,TRUE),
('Mango Sticky Rice','HIHI-MANGO-STICKY-RICE','Dessert','HIHI TomYum','Golden mango, creamy coconut and warm sticky rice.','<p>Thailand’s happiest ending: sweet, creamy and a little salty.</p>','/hihitomyum/images/hihi-mango-sticky-rice.png','/hihitomyum/images/hihi-mango-sticky-rice.png','/hihitomyum/images/hihi-mango-sticky-rice.png','Sweet','hihi-menu','mango sticky rice, Thai dessert, HIHI',59000,0,'VND','en','mango-sticky-rice',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,TRUE);
COMMIT;
