-- PostgreSQL destructive seed for cloned schema/database: real-estate.anhmedia.vn
-- Run ONLY against the new cloned tenant database. All listings and prices are demo data.
BEGIN;
TRUNCATE TABLE public.articletb, public.producttb RESTART IDENTITY CASCADE;
INSERT INTO public.articletb(articleid,username,articlelink,articlecategory,articlelangcode,articlesubcategory,articletitle,articlekeyword,articlethumnailurl,articledescription,articlecontent,createdtime,modifiedtime,isvisible,isapproved,islocked,rejectedbyuser,rejectedreason,articletime,originauthor,menustringid,viewcount,rating,postid,articletemplate,"index") VALUES
('NEXA-HOME','none','home','page','vi','none','NEXA Estate — Bất động sản cho một tương lai khác biệt','bất động sản cao cấp, đầu tư, NEXA Estate','/real-estate.anhmedia.vn/images/property-panorama.png','Danh mục bất động sản cao cấp và dịch vụ tư vấn đầu tư minh bạch.','<p>Trang chủ NEXA Estate.</p>',NOW(),NOW(),TRUE,TRUE,FALSE,'none','none',NOW(),'NEXA Estate','none',0,0,'n','index.html','0'),
('NEXA-PROPERTIES','none','products.html','page','vi','none','Danh mục bất động sản — NEXA Estate','căn hộ, biệt thự, nghỉ dưỡng','/real-estate.anhmedia.vn/images/residence-one.png','Các bất động sản cao cấp được tuyển chọn.','<p>Danh mục dự án NEXA Estate.</p>',NOW(),NOW(),TRUE,TRUE,FALSE,'none','none',NOW(),'NEXA Estate','none',0,0,'n','products.html','1');
INSERT INTO public.producttb(productname,productcode,productcatalog,productbrand,productshortdes,productlongdes,productimageurl1,productimageurl2,productimagedesurl,productsubcatalog,productgroupstring,pagekeyword,productpriceamount,productdiscont,productpricecurrency,language,path,createdtime,publishedtime,modifiedtime,isvisible,isapproved,islocked,isnew) VALUES
('Azure Palm Villa','NEXA-AZURE-PALM','Biệt thự','NEXA Estate','Thảo Điền · 4 phòng ngủ · 420 m²','<h2>Biệt thự nhiệt đới giữa lòng thành phố</h2><p>Không gian mở, hồ bơi riêng và khu vườn nhiều lớp tại khu dân cư yên tĩnh ở Thảo Điền.</p><ul><li>Diện tích đất: 520 m²</li><li>Diện tích sử dụng: 420 m²</li><li>4 phòng ngủ, 5 phòng tắm</li><li>Pháp lý minh bạch</li></ul><p><em>Thông tin và giá chỉ dùng cho bản demo.</em></p>','/real-estate.anhmedia.vn/images/villa-azure.png','/real-estate.anhmedia.vn/images/villa-azure.png','/real-estate.anhmedia.vn/images/villa-azure.png','Nhà ở','nexa-properties','biệt thự Thảo Điền, hồ bơi, NEXA',32500000000,0,'VND','vi','azure-palm-villa',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,TRUE),
('NEXA One Residence','NEXA-ONE-RESIDENCE','Căn hộ','NEXA Estate','Thủ Thiêm · 3 phòng ngủ · 168 m²','<h2>Tầm nhìn mới tại trung tâm tài chính</h2><p>Căn hộ tầng cao với mặt kính toàn cảnh, tiện ích riêng tư và kết nối trực tiếp trung tâm thành phố.</p><ul><li>Diện tích: 168 m²</li><li>3 phòng ngủ, 3 phòng tắm</li><li>2 chỗ đậu xe</li><li>Bàn giao hoàn thiện cao cấp</li></ul><p><em>Thông tin và giá chỉ dùng cho bản demo.</em></p>','/real-estate.anhmedia.vn/images/residence-one.png','/real-estate.anhmedia.vn/images/residence-one.png','/real-estate.anhmedia.vn/images/residence-one.png','Căn hộ cao cấp','nexa-properties','căn hộ Thủ Thiêm, view sông, NEXA',12800000000,0,'VND','vi','nexa-one-residence',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,TRUE),
('Solara Coastal Retreat','NEXA-SOLARA-COASTAL','Nghỉ dưỡng','NEXA Estate','Cam Ranh · 3 phòng ngủ · 310 m²','<h2>Nơi đường chân trời chạm vào ngôi nhà</h2><p>Biệt thự nghỉ dưỡng hướng biển với hồ bơi vô cực, dịch vụ quản gia và chương trình quản lý cho thuê.</p><ul><li>Diện tích đất: 460 m²</li><li>3 phòng ngủ hướng biển</li><li>Hồ bơi và sân vườn riêng</li><li>Chương trình vận hành tùy chọn</li></ul><p><em>Thông tin và giá chỉ dùng cho bản demo.</em></p>','/real-estate.anhmedia.vn/images/coastal-retreat.png','/real-estate.anhmedia.vn/images/coastal-retreat.png','/real-estate.anhmedia.vn/images/coastal-retreat.png','Biệt thự biển','nexa-properties','biệt thự biển Cam Ranh, nghỉ dưỡng, NEXA',18900000000,0,'VND','vi','solara-coastal-retreat',NOW(),NOW(),NOW(),TRUE,TRUE,FALSE,TRUE);
COMMIT;
-- Backend tenant mapping required:
-- <config name="templateFolder" tenantId="real-estate.anhmedia.vn"><language code="en">real-estate.anhmedia.vn</language></config>
