#Created by super-user customer provisioning
#Sun Aug 16 09:26:23 ICT 2026
id=phuonganhamara.anhmedia.vn
password=295hAhVyG5Manager
url=jdbc\:postgresql\://localhost\:5432/phuonganhamara
username=postgres
